[package]
name = "headesk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mini_gl_fb = "0.9.0"
gl = "0.10.0"
opencv = "0.53.2"
